# -*- coding: utf-8 -*-
"""aiass

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GG-vAiZGvFecbG7SwO58cLhvDafRvzd7
"""

# Import basic libraries
import pandas as pd
import numpy as np
import re
import pickle
import streamlit as st

# NLP libraries
import nltk
nltk.download('punkt_tab')
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('averaged_perceptron_tagger_eng')
nltk.download('maxent_ne_chunker_tab')
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

# Machine learning libraries
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.svm import LinearSVC
from sklearn.naive_bayes import MultinomialNB
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report




labels = {
    0: "Negative",
    1: "Neutral",
    2: "Positive",
}

def detect_comment(text):

    cleaned = clean_text(text)

    if cleaned == "":
        return "Neutral"

    vector = vectorizer.transform([cleaned])

    prediction = svm_model.predict(vector)[0]

    return labels[prediction]

print(detect_comment("I love this product"))
print(detect_comment("shit"))
print(detect_comment("fuck"))
print(detect_comment("nigger"))
print(detect_comment("The result was disappointing"))
print(detect_comment("This phone works perfectly"))
print(detect_comment("Worst service ever"))
print(detect_comment("The meeting is tomorrow"))
print(detect_comment("99"))
print(detect_comment("??"))


